### ISSUE TITLE
Request for adding a video thumbnail url to the results. 

### ISSUE THREAD

**Issue by lortiz-nativo** [epctex/tiktok-video-downloader#1]
A thumbnail download url would be useful. Currently I have to generate the thumbnail myself using the video file.

**Comment by tugkan** [comment]
Hey @lortiz-nativo !

Thank you very much for reaching out. After your request, we just integrated the `cover` attribute for the objects. You can use the latest version for the best experience.

Please let me know if there are any other things that I can assist you with,
Best
